### ISSUE TITLE
Canvas+

### ISSUE THREAD

**Issue by mfpekala** [mpekala23/play-jpeg#1]
## Todos
- [x] Tweak the onMouseLeave/penDown logic to make it more natural
- [x] Proper menu bar below the canvas
- [x] RGB picker only shows up on click
- [x] Eyedropper tool
- [x] Premade 8x8 drawings
- [x] Popup frame to select an 8x8 square from a larger image
