### ISSUE TITLE
QTable+

### ISSUE THREAD

**Issue by mpekala23** [mpekala23/play-jpeg#2]
## Todos
- [ ] Menu bar below the QTable
- [ ] Randomize QTable option
- [ ] Premade QTable options
- [ ] Better editing feel (either always select all, or move cursor to end, something)
