### ISSUE TITLE
Background and motivation

### ISSUE THREAD

**Issue by mpekala23** [mpekala23/play-jpeg#3]
## Todos
- [ ] Write an overview section
- [ ] Write a section explaining JPEG compression (subsection for compression, QTable, decompression)
- [ ] Write an about/by section
