### ISSUE TITLE
Share Experience

### ISSUE THREAD

**Issue by mpekala23** [mpekala23/play-jpeg#5]
## Todos
- [ ] Make social for play-JPEG
- [ ] Create well-integrated share buttons
- [ ] Way to dehydrate/rehydrate canvas/QTable efficiently in the URL
